[platformio]
default_envs = atom_lite
src_dir = firmware/usb_bootstrap
build_dir = .arduino/build/platformio
extra_configs = .arduino/tmp/platformio-local.ini

[env:atom_lite]
platform = https://github.com/platformio/platform-espressif32.git#76b0e9b942330979860e3bc7fd3b92b383d66cc1
board = m5stack-atom
framework = arduino
build_type = release
board_build.partitions = partitions/dmbridge_ota.csv
upload_speed = 115200
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -Werror
    -flto
build_unflags =
    -fno-lto
extra_scripts =
    post:scripts/platformio_image_gate.py
