#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BOARDS=("atoms3-lite" "atom-lite")

COMMIT=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILT_AT=$(date -u +%FT%TZ)
cat > "$ROOT/shared/src/build_info.h" <<EOF
#pragma once

// Generated by tools/sync_shared.sh — DO NOT EDIT
#define BUILD_COMMIT "$COMMIT"
#define BUILD_AT     "$BUILT_AT"
EOF

node "$ROOT/tools/embed_web_ui.mjs"

for board in "${BOARDS[@]}"; do
  mkdir -p "$ROOT/firmware/$board/src" "$ROOT/firmware/$board/data"
  rsync -a --delete "$ROOT/shared/src/" "$ROOT/firmware/$board/src/"
  rsync -a --delete "$ROOT/shared/data/" "$ROOT/firmware/$board/data/"
done
